### ISSUE TITLE
Malformed HTTP error with Python Asyncio Websockets default example

### ISSUE THREAD

**Issue by damouse** [daltoniam/Starscream#402]
Im unable to connect to a websocket server written with python 3.6.2 using the popular python library `websockets` on version 3.4 (latest.) I'm posting this here because the next most popular Swift ws library after Starscream, [SwiftWebSockets,](https://github.com/tidwall/SwiftWebSocket) works out of the box so I'm assuming If there is a bug, and not some configuration error on my part, it may be on the part of Starscream.

Sample swift code, running in an iOS simulator using v3.0.2:

```
import Starscream

class TestClient: WebSocketDelegate {
    var ws: WebSocket!
    
    init() {
        ws = WebSocket(url: URL(string: "ws://0.0.0.0:9876")!)
        ws.delegate = self
        ws.connect()
    }
    
    func websocketDidConnect(socket: WebSocketClient) {
        print("didConnect")
    }
    
    func websocketDidDisconnect(socket: WebSocketClient, error: Error?) {
        print("didDisconnect")
    }
    
    func websocketDidReceiveMessage(socket: WebSocketClient, text: String) {
        print("received Message: \(text)")
    }
    
    func websocketDidReceiveData(socket: WebSocketClient, data: Data) {
        print("received Data: \(data)")
    }
}

let t = TestClient()
```

Websockets/Asyncio default example: 

```
import asyncio
import websockets


async def hello(websocket, path):
    name = await websocket.recv()
    print("< {}".format(name))

    greeting = "Hello {}!".format(name)
    await websocket.send(greeting)
    print("> {}".format(greeting))

start_server = websockets.serve(hello, 'localhost', 9876)

asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()
```

And the errors, on python's side:

```
Invalid handshake
Traceback (most recent call last):
  File "/Users/damouse/.local/share/virtualenvs/field-software-uS6R5hDc/lib/python3.6/site-packages/websockets/server.py", line 174, in read_http_request
    path, headers = yield from read_request(self.reader)
  File "/Users/damouse/.local/share/virtualenvs/field-software-uS6R5hDc/lib/python3.6/site-packages/websockets/http.py", line 77, in read_request
    request_line = yield from read_line(stream)
  File "/Users/damouse/.local/share/virtualenvs/field-software-uS6R5hDc/lib/python3.6/site-packages/websockets/http.py", line 195, in read_line
    raise ValueError("Line without CRLF")
ValueError: Line without CRLF

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/damouse/.local/share/virtualenvs/field-software-uS6R5hDc/lib/python3.6/site-packages/websockets/server.py", line 69, in handler
    extra_headers=self.extra_headers)
  File "/Users/damouse/.local/share/virtualenvs/field-software-uS6R5hDc/lib/python3.6/site-packages/websockets/server.py", line 297, in handshake
    path, request_headers = yield from self.read_http_request()
  File "/Users/damouse/.local/share/virtualenvs/field-software-uS6R5hDc/lib/python3.6/site-packages/websockets/server.py", line 176, in read_http_request
    raise InvalidMessage("Malformed HTTP message") from exc
websockets.exceptions.InvalidMessage: Malformed HTTP message
```

For reference, here's the working SwiftWebSocket code:

```
import SwiftWebSocket

class TestClient {
    var ws: WebSocket!
    
    init() {
        ws = WebSocket("ws://0.0.0.0:9876")
        
        ws.event.open = {
            print("opened")
            self.ws.send("Hello")
        }

        ws.event.close = { code, reason, clean in
            print("close")
        }

        ws.event.error = { error in
            print("error \(error)")
        }

        ws.event.message = { message in
            if let text = message as? String {
                print("recv: \(text)")
            }
        }
    }
}

let t = TestClient()
```

Which correctly connects, and shows output from python: 
```
< Hello!
> Hello Hello!!
```

If this doesn't fall under your purview, no worries, just thought it better to have an issue posted instead of letting an error slip by.

**Comment by acmacalister** [comment]
I just tried it on my end with the latest version of Starscream, Python, Websockets and Asyncio and it worked fine. Do you any other info? Are you sending any custom headers or is that exact code you are using above?

**Comment by purefan** [comment]
Im having the same problem with this:
```
#!/usr/bin/env python

# WS client example

import asyncio
import websockets

async def hello():
    async with websockets.connect('ws://localhost:3000') as websocket:
        name = input("What's your name? ")

        await websocket.send(name)
        print(f"> {name}")

        greeting = await websocket.recv()
        print(f"< {greeting}")

asyncio.get_event_loop().run_until_complete(hello())
```

**Comment by eduardogoncalves** [comment]
@purefan Hi, the code you've posted is the example code from https://websockets.readthedocs.io/en/stable/. I'm having same issue.
I'm running it inside a docker's container, and I'm tryng to connect outside the container, and doing this, it gives me an error: "raise ValueError("Line without CRLF") "
But if I run both server and client inside the same container it works. I didn't figured out yet what's wrong.

Are you running it on a docker container too?

**Comment by eduardogoncalves** [comment]
@damouse @purefan I soved it by instead of using `localhost`, use `0.0.0.0` at server file:
```
import asyncio
import websockets


async def hello(websocket, path):
    name = await websocket.recv()
    print("< {}".format(name))

    greeting = "Hello {}!".format(name)
    await websocket.send(greeting)
    print("> {}".format(greeting))

start_server = websockets.serve(hello, '0.0.0.0', 9876)

asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()
```
